### ISSUE TITLE
Translate the code from C# to C++

### ISSUE THREAD

**Issue by Konard** [linksplatform/Random#24]
600 RUB reward can be claimed by anyone who completes this task.

**Comment by uselessgoddess** [comment]
What do you propose replace ```System.Random```?

**Comment by Konard** [comment]
> What do you propose replace `System.Random`?

Something with similar characteristics: https://docs.microsoft.com/en-us/dotnet/api/system.random?view=net-5.0#remarks

**Comment by norwend** [comment]
We can basically use [std::mt19937 or std::mt19937_64](https://en.cppreference.com/w/cpp/numeric/random/mersenne_twister_engine) (for 64-bit numbers) with [uniform_int_distribution](https://en.cppreference.com/w/cpp/numeric/random/uniform_int_distribution) where we can put our Ranges

**Comment by norwend** [comment]
The [<random>](https://en.cppreference.com/w/cpp/header/random) header has pretty much all we need

**Comment by norwend** [comment]
If needed, we can wrap the PRNG into another class (but I don't really think it's worth it)

**Comment by uselessgoddess** [comment]
`charp` version do not use `System.Random` in the return statements
We can use next style:
```cpp
namespace ... 
{
     bool NextBool()
     {
          auto generator = make_mt19937();
          std::uniform_int_distribution<> random(0, 1);
          return random(generator);
     }
     
     bool NextBool(const std::mt19937& generator)
     {
          std::uniform_int_distribution<> random(0, 1);
          return random(generator);
     }
}
```

**Comment by uselessgoddess** [comment]
OR)))
```cpp
     bool NextBool()
     {
          return rand() % 2;
     }
```

**Comment by Konard** [comment]
Do we need to use [std::knuth_b](https://en.cppreference.com/w/cpp/numeric/random/shuffle_order_engine)?

**Comment by uselessgoddess** [comment]
This might make the user dependent `std::knuth_b`

**Comment by norwend** [comment]
> Do we need to use [std::knuth_b](https://en.cppreference.com/w/cpp/numeric/random/shuffle_order_engine)?

I don't really think so. The default engines are pretty good at generating random numbers

**Comment by uselessgoddess** [comment]
`default engines`?

**Comment by norwend** [comment]
I mean, the ones which are defined in the <random> header without any additional shuffling

**Comment by norwend** [comment]
I want to return the reward

**Comment by Konard** [comment]
> I want to return the reward

Thank you. This reward will be used for other LinksPlatform priority issues.
